require(shiny)
require(freeCarto)
require(sp)
require(cluster)
require(FactoMineR)
require(sjPlot)
library(ggplot2)
load("TNdeleg.RData")
baseData <- reactiveValues(spdf = TNdeleg.spdf, data = TNdeleg)
pcaData <- reactiveValues(acpRes = NA)